config/routes.rb
B3::Application.routes.draw do
  resources :battlestar_galacticas

  resources :bears

  resources :beets

end

app/models/battlestar_galactica.rb
class BattlestarGalactica < ActiveRecord::Base
  attr_accessible :actor, :character, :quote
end

app/models/bear.rb
class Bear < ActiveRecord::Base
  attr_accessible :color, :description, :habitat, :picture, :name
end

app/models/beet.rb
class Beet < ActiveRecord::Base
  attr_accessible :color, :description, :name, :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/battlestar_galacticas_controller.rb
class BattlestarGalacticasController < ApplicationController
  # GET /battlestar_galacticas
  # GET /battlestar_galacticas.json
  def index
    @battlestar_galacticas = BattlestarGalactica.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @battlestar_galacticas }
    end
  end

  # GET /battlestar_galacticas/1
  # GET /battlestar_galacticas/1.json
  def show
    @battlestar_galactica = BattlestarGalactica.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @battlestar_galactica }
    end
  end

  # GET /battlestar_galacticas/new
  # GET /battlestar_galacticas/new.json
  def new
    @battlestar_galactica = BattlestarGalactica.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @battlestar_galactica }
    end
  end

  # GET /battlestar_galacticas/1/edit
  def edit
    @battlestar_galactica = BattlestarGalactica.find(params[:id])
  end

  # POST /battlestar_galacticas
  # POST /battlestar_galacticas.json
  def create
    @battlestar_galactica = BattlestarGalactica.new(params[:battlestar_galactica])

    respond_to do |format|
      if @battlestar_galactica.save
        format.html { redirect_to @battlestar_galactica, notice: 'Battlestar galactica was successfully created.' }
        format.json { render json: @battlestar_galactica, status: :created, location: @battlestar_galactica }
      else
        format.html { render action: "new" }
        format.json { render json: @battlestar_galactica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /battlestar_galacticas/1
  # PUT /battlestar_galacticas/1.json
  def update
    @battlestar_galactica = BattlestarGalactica.find(params[:id])

    respond_to do |format|
      if @battlestar_galactica.update_attributes(params[:battlestar_galactica])
        format.html { redirect_to @battlestar_galactica, notice: 'Battlestar galactica was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @battlestar_galactica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battlestar_galacticas/1
  # DELETE /battlestar_galacticas/1.json
  def destroy
    @battlestar_galactica = BattlestarGalactica.find(params[:id])
    @battlestar_galactica.destroy

    respond_to do |format|
      format.html { redirect_to battlestar_galacticas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/bears_controller.rb
class BearsController < ApplicationController
  # GET /bears
  # GET /bears.json
  def index
    @bears = Bear.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bears }
    end
  end

  # GET /bears/1
  # GET /bears/1.json
  def show
    @bear = Bear.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bear }
    end
  end

  # GET /bears/new
  # GET /bears/new.json
  def new
    @bear = Bear.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bear }
    end
  end

  # GET /bears/1/edit
  def edit
    @bear = Bear.find(params[:id])
  end

  # POST /bears
  # POST /bears.json
  def create
    @bear = Bear.new(params[:bear])

    respond_to do |format|
      if @bear.save
        format.html { redirect_to @bear, notice: 'Bear was successfully created.' }
        format.json { render json: @bear, status: :created, location: @bear }
      else
        format.html { render action: "new" }
        format.json { render json: @bear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bears/1
  # PUT /bears/1.json
  def update
    @bear = Bear.find(params[:id])

    respond_to do |format|
      if @bear.update_attributes(params[:bear])
        format.html { redirect_to @bear, notice: 'Bear was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bears/1
  # DELETE /bears/1.json
  def destroy
    @bear = Bear.find(params[:id])
    @bear.destroy

    respond_to do |format|
      format.html { redirect_to bears_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/beets_controller.rb
class BeetsController < ApplicationController
  # GET /beets
  # GET /beets.json
  def index
    @beets = Beet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beets }
    end
  end

  # GET /beets/1
  # GET /beets/1.json
  def show
    @beet = Beet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beet }
    end
  end

  # GET /beets/new
  # GET /beets/new.json
  def new
    @beet = Beet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beet }
    end
  end

  # GET /beets/1/edit
  def edit
    @beet = Beet.find(params[:id])
  end

  # POST /beets
  # POST /beets.json
  def create
    @beet = Beet.new(params[:beet])

    respond_to do |format|
      if @beet.save
        format.html { redirect_to @beet, notice: 'Beet was successfully created.' }
        format.json { render json: @beet, status: :created, location: @beet }
      else
        format.html { render action: "new" }
        format.json { render json: @beet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beets/1
  # PUT /beets/1.json
  def update
    @beet = Beet.find(params[:id])

    respond_to do |format|
      if @beet.update_attributes(params[:beet])
        format.html { redirect_to @beet, notice: 'Beet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beets/1
  # DELETE /beets/1.json
  def destroy
    @beet = Beet.find(params[:id])
    @beet.destroy

    respond_to do |format|
      format.html { redirect_to beets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battlestar_galacticas_helper.rb
module BattlestarGalacticasHelper
end

app/helpers/bears_helper.rb
module BearsHelper
end

app/helpers/beets_helper.rb
module BeetsHelper
end

app/views/battlestar_galacticas/_form.html.erb
<%= form_for(@battlestar_galactica) do |f| %>
  <% if @battlestar_galactica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@battlestar_galactica.errors.count, "error") %> prohibited this battlestar_galactica from being saved:</h2>

      <ul>
      <% @battlestar_galactica.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actor %><br />
    <%= f.text_field :actor %>
  </div>
  <div class="field">
    <%= f.label :character %><br />
    <%= f.text_field :character %>
  </div>
  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/battlestar_galacticas/edit.html.erb
<h1>Editing battlestar_galactica</h1>

<%= render 'form' %>

<%= link_to 'Show', @battlestar_galactica %> |
<%= link_to 'Back', battlestar_galacticas_path %>

app/views/battlestar_galacticas/index.html.erb
<h1>Listing battlestar_galacticas</h1>

<table>
  <tr>
    <th>Actor</th>
    <th>Character</th>
    <th>Quote</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @battlestar_galacticas.each do |battlestar_galactica| %>
  <tr>
    <td><%= battlestar_galactica.actor %></td>
    <td><%= battlestar_galactica.character %></td>
    <td><%= battlestar_galactica.quote %></td>
    <td><%= link_to 'Show', battlestar_galactica %></td>
    <td><%= link_to 'Edit', edit_battlestar_galactica_path(battlestar_galactica) %></td>
    <td><%= link_to 'Destroy', battlestar_galactica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Battlestar galactica', new_battlestar_galactica_path %>

app/views/battlestar_galacticas/new.html.erb
<h1>New battlestar_galactica</h1>

<%= render 'form' %>

<%= link_to 'Back', battlestar_galacticas_path %>

app/views/battlestar_galacticas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Actor:</b>
  <%= @battlestar_galactica.actor %>
</p>

<p>
  <b>Character:</b>
  <%= @battlestar_galactica.character %>
</p>

<p>
  <b>Quote:</b>
  <%= @battlestar_galactica.quote %>
</p>


<%= link_to 'Edit', edit_battlestar_galactica_path(@battlestar_galactica) %> |
<%= link_to 'Back', battlestar_galacticas_path %>

app/views/bears/_form.html.haml
= form_for(@bear) do |f|
  - if @bear.errors.any?
    #error_explanation
      %h2
        = pluralize(@bear.errors.count, "error")
        prohibited this bear from being saved:
      %ul
        - @bear.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :color
    %br
    = f.text_field :color
  .field
    = f.label :description
    %br
    = f.text_area :description
  .field
    = f.label :habitat
    %br
    = f.text_field :habitat
  .field
    = f.label :picture
    %br
    = f.text_field :picture
  .actions
    = f.submit

app/views/bears/edit.html.haml
%h1 Editing bear

= render 'form'

= link_to 'Show', @bear
|
= link_to 'Back', bears_path

app/views/bears/index.html.haml
%h1 Listing Bears

%table
  %tr
    %th Name
    %th Color
    %th Description
    %th Habitat
    %th Picture
    %th 
    %th 
    %th 

  - @bears.each do |bear|
    %tr
      %td= bear.name 
      %td= bear.color 
      %td= bear.description 
      %td= bear.habitat 
      %td= bear.picture 
      %td= link_to 'Show', bear 
      %td= link_to 'Edit', edit_bear_path(bear) 
      %td= link_to 'Destroy', bear, method: :delete, data: { confirm: 'Are you sure?' } 


%br

= link_to 'New Bear', new_bear_path

app/views/bears/new.html.haml
%h1 New bear

= render 'form'

= link_to 'Back', bears_path

app/views/bears/show.html.haml
%p#notice= flash[:notice]

%p
  %strong Name
  = @bear.name

%p
  %strong Color
  = @bear.color

%p
  %strong Description
  = @bear.description

%p
  %strong Habitat
  = @bear.habitat

%p
  %strong Picture
  = @bear.picture

= link_to 'Edit', edit_bear_path(@bear)
|
= link_to 'Back', bears_path
|
= link_to 'Delete', bears_path(@bear), method: "delete", data: {confirm: 'Are you sure?'}

app/views/beets/_form.html.erb
<%= form_for(@beet) do |f| %>
  <% if @beet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beet.errors.count, "error") %> prohibited this beet from being saved:</h2>

      <ul>
      <% @beet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beets/edit.html.erb
<h1>Editing beet</h1>

<%= render 'form' %>

<%= link_to 'Show', @beet %> |
<%= link_to 'Back', beets_path %>

app/views/beets/index.html.erb
<h1>Listing beets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Description</th>
    <th>Picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beets.each do |beet| %>
  <tr>
    <td><%= beet.name %></td>
    <td><%= beet.color %></td>
    <td><%= beet.description %></td>
    <td><%= beet.picture %></td>
    <td><%= link_to 'Show', beet %></td>
    <td><%= link_to 'Edit', edit_beet_path(beet) %></td>
    <td><%= link_to 'Destroy', beet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beet', new_beet_path %>

app/views/beets/new.html.erb
<h1>New beet</h1>

<%= render 'form' %>

<%= link_to 'Back', beets_path %>

app/views/beets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beet.name %>
</p>

<p>
  <b>Color:</b>
  <%= @beet.color %>
</p>

<p>
  <b>Description:</b>
  <%= @beet.description %>
</p>

<p>
  <b>Picture:</b>
  <%= @beet.picture %>
</p>


<%= link_to 'Edit', edit_beet_path(@beet) %> |
<%= link_to 'Back', beets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>B3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>